### ISSUE TITLE
Power and heat

### ISSUE THREAD

**Issue by SovrignJr** [DaveRainbowin/nuclearIncremental#1]
**Describe the bug**
When i placed a cell down and proceeded to remove it the power and the heat were rising without there being a cell present.

**To Reproduce**
1. Go to 'cells'
2. Click on 'cells'

**Expected behavior**
expected the power and heat not to rise

**Screenshots**
![image](https://user-images.githubusercontent.com/63425695/78937917-2f4f2880-7aa9-11ea-9be0-f251db05356b.png)

**Context**
 - Google chrome

**Additional context**

**Comment by DaveRainbowin** [comment]
I will fix this soon. Thank you!

**Comment by DaveRainbowin** [comment]
This is been fixed as of now!
