### ISSUE TITLE
clicking is broke

### ISSUE THREAD

**Issue by osaniXian** [DaveRainbowin/nuclearIncremental#2]
**Describe the bug**
the clicked h tanks don't become normal again once you place them and you can highlight more then one

**To Reproduce**
1. Go to 'https://daverainbowin.github.io/nuclearIncremental/'
2. Click on '1'st h tank'
3. then click on 'second h tank'

**Expected behavior**
first h tank should become ungreen

**Screenshots**
![Capture](https://user-images.githubusercontent.com/52901450/78943612-1165d180-7a71-11ea-8c76-b6b5643e2c19.PNG)

**Context**
 - Brave browser

**Additional context**

**Comment by DaveRainbowin** [comment]
Will fix this later too!

**Comment by osaniXian** [comment]
thx

**Comment by DaveRainbowin** [comment]
Could you improve the grammar and whatnot?

**Comment by DaveRainbowin** [comment]
Actually, this isn't very important.

**Comment by DaveRainbowin** [comment]
ok, i think i can fix this when i get home

**Comment by DaveRainbowin** [comment]
released
