### ISSUE TITLE
power and heat

### ISSUE THREAD

**Issue by silverhydra6078** [DaveRainbowin/nuclearIncremental#4]
**Describe the bug**
the power and heat increases with each cell even when they dont exist
**To Reproduce**
1. Go to 'cells'
2. Click on 'any cell'
3. place cell on map
4. remove cell from map
5. replace cell on map
6. remove cell from map.
7. repeat
8. See error

**Expected behavior**

**Screenshots**

**Context**
 - Browser

**Additional context**

**Comment by DaveRainbowin** [comment]
See #1
